Auth\RegistrationBundle\Entity\Users:
        protperities:
              name:
                  - Type:
                          type: string
                          message: The value {{ value }} is not a valid {{ type }}.
                  - NotBlank: ~
                  - Length:
                         min: 5