Form\RegistrationBundle\Entity\Roles:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }

#    oneToMany:
#        users:
#            targetEntity: Users
#            mappedBy: roles