Form\RegistrationBundle\Entity\Roles:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        role:
            type: string
            length: 255
    lifecycleCallbacks: {  }

    oneToMany:
        users:
            targetEntity: User
            mappedBy: role