# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Form\RegistrationBundle\Entity\Users:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        our_db_provider:
            entity:
                class: FormRegistrationBundle:Users
                property: email
                # if you're using multiple entity managers
                # manager_name: customer


    firewalls:
        # order matters! This must be before the ^/ firewall
      main:
                 anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }

