form_registration_showUsers:
    resource: "@FormRegistrationBundle/Resources/config/routing/users.yml"
    prefix:   /showUsers

#registration
form_registration_homepage:
    path:     /registration
    defaults: { _controller: FormRegistrationBundle:Default:index }


registration_success:
    path:     /registration_success
    defaults: { _controller: FormRegistrationBundle:Default:registration }

#login
login:
    path:     /login
    defaults: { _controller: FormRegistrationBundle:Default:login }

auth_success:
    path:     /auth_success
    defaults: { _controller: FormRegistrationBundle:Default:authSuccess }

#admin
admin_homepage:
    path:     /admin
    defaults: { _controller: FormRegistrationBundle:Admin:main }

admin_users:
    path:     /admin/users
    defaults: { _controller: FormRegistrationBundle:Admin:showUsers }

#ajax
validate_password:
    path:     /ajax
    defaults: { _controller: FormRegistrationBundle:Ajax:validatePassword }
