form_registration_homepage:
    path:     /registration
    defaults: { _controller: FormRegistrationBundle:Default:index }


registration_success:
    path:     /registration_success
    defaults: { _controller: FormRegistrationBundle:Default:registration }


login:
    path:     /login
    defaults: { _controller: FormRegistrationBundle:Default:login }

#login:
#    path:     /login
#    defaults: { _controller: FormRegistrationBundle:Security:login }


auth_success:
    path:     /auth_success
    defaults: { _controller: FormRegistrationBundle:Default:authSuccess }


login_check:
  pattern:   /login_check