Form\RegistrationBundle\Entity\Users:
    constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        name:
            - NotBlank: ~
            - Length:
                    min: 4
        email:
            - NotBlank: ~
            - Email:
                    message: The email {{ value }} is not a valid email.
            - Length:
                    min: 4
        password:
            - NotBlank: ~
            - Length:
                    min: 4
                    max: 15
            - Regex: '/^[a-z0-9_-]{1,18}$/'
        roles:
           - Valid: ~



Form\RegistrationBundle\Entity\Roles:
    properties:
        name:
            - Choice:
                choices:  [ROLE_ADMIN, ROLE_USER]


